"""updates association table

Revision ID: 7b44f0673e0b
Revises: d85a5b68dd8d
Create Date: 2023-10-31 08:50:01.837028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b44f0673e0b'
down_revision = 'd85a5b68dd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
