"""updates association table

Revision ID: ab98307ee091
Revises: 
Create Date: 2023-10-30 17:10:50.885765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab98307ee091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('header', sa.String(length=30), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], name=op.f('fk_posts_poster_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('replier_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['replier_id'], ['users.id'], name=op.f('fk_replies_replier_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_reply',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_reply_post_id_posts')),
    sa.ForeignKeyConstraint(['reply_id'], ['replies.id'], name=op.f('fk_post_reply_reply_id_replies'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_reply')
    op.drop_table('replies')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
